### ISSUE TITLE
step_by_step_cifar10 does not exist (plus other issues)

### ISSUE THREAD

**Issue by wielandbrendel** [pikinder/nn-patterns#1]
First and foremost thanks for releasing the code for PatternNet! I am very interested to use your method but I have lots of troubles getting the code to work. Among the issues I found are:

1. The step_by_step_cifar10.py script does not exist but it would be really helpful to see the whole chain from computing patterns to getting explanations.
2. When computing the combined patterns (as suggested by the Readme) one gets 'basic', 'positive_x' and 'negative_y' keys, but I am not sure which one I am supposed to use in the explainer?
3. In the examples, neither the link to the VGG-16 weights nor to the patterns still works.

I am still fighting to compute the patterns for my VGG-16 (it fails with some reshape errors) but these might be issues on my end.

**Comment by albermax** [comment]
Sorry about the late response. 
There is a new software: https://github.com/albermax/innvestigate
